[build]
  command = "npm install @rollup/rollup-linux-x64-gnu @rollup/rollup-linux-x64-musl --no-save --platform=linux --arch=x64 && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  ROLLUP_SKIP_PLATFORM_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
